<?php
/**
 * @var \Codilar\Employee\Block\View $block
 */
$employees = $block->getAllEmp();
?>
<div class="employee-listing">
    <h1>Our Employee List</h1>
    <span>
        <a href="<?php echo $block->getFormUrl()?>"><button style="background-color:#514943;color:white;color:white;">Add New Employee</button></a>
    </span>
    <?php if (count($employees) > 0): ?>
        <table>
            <thead>
            <tr>
                <th><?php echo __('Id') ?></th>
                <th><?php echo __('Name') ?></th>
                <th><?php echo __('Action') ?></th>
            </tr>
            <?php foreach ($block->getAllEmp() as $employee): ?>
                <tr>
                    <td><?php echo $employee->getEntityId()?></td>
                    <td><?php echo $employee->getName() ?></td>
                    <td>
                        <span>
                            <a href="<?php echo $block->getFormUrl(). 'entity_id/' . $employee->getEntityId()?>"><button style="background-color:#514943;color:white;">Edit</button></a>
                        </span>
                        <span>
                            <a href="<?php echo $block->getDeleteUrl(). 'entity_id/' . $employee->getEntityId()?>"><button style="background-color:#514943;color:white;">Delete</button></a>
                        </span>
                        <span>
                            <a href="<?php echo $block->getDetailslUrl(). 'entity_id/' . $employee->getEntityId()?>"><button style="background-color:#514943;color:white;">View</button></a>
                        </span>
                    </td> 
                </tr>
            <?php endforeach; ?>
            </thead>
        </table>
    <?php else: ?>
        <h3>Employee List is Empty</h3>
    <?php endif; ?>
</div>
